# Generated by Django 4.1.3 on 2023-03-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_nuevo_card',
            name='img_card',
            field=models.FileField(null=True, upload_to='img_upload'),
        ),
    ]
