# Generated by Django 4.1.3 on 2023-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_create_nuevo_curso_form_carga_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='form_carga_curso',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='img_curso',
            field=models.CharField(max_length=300),
        ),
    ]
