# Generated by Django 4.1.3 on 2023-03-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_create_nuevo_curso_form_carga_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='personal_cursos',
            field=models.CharField(max_length=200),
        ),
    ]
