# Generated by Django 4.1.3 on 2023-03-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_create_nuevo_curso_personal_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_nuevo_publicacion',
            name='descripcion_pub',
        ),
        migrations.AddField(
            model_name='create_nuevo_publicacion',
            name='descrip_pub',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='create_nuevo_publicacion',
            name='img_pub',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AlterField(
            model_name='create_nuevo_card',
            name='cargo_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_card',
            name='descrip_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_card',
            name='img_card',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='create_nuevo_card',
            name='nombre_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='descrip_corta_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='descrip_larga_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='hospital_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='nombre_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='personal_cursos',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='requisitos_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='servicio_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_nuevo_publicacion',
            name='nombre_pub',
            field=models.CharField(max_length=100),
        ),
    ]
