# Generated by Django 4.1.3 on 2023-04-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_create_nuevo_publicacion_descripcion_pub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_card',
            name='img_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
