# Generated by Django 4.1.3 on 2023-04-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_create_nuevo_card_img_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='img_curso',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='create_nuevo_publicacion',
            name='img_pub',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
