# Generated by Django 4.1.3 on 2023-04-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_create_nuevo_curso_img_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='form_carga_curso',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
