# Generated by Django 4.1.3 on 2023-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_create_nuevo_curso_form_carga_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='form_carga_curso',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='img_curso',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
