# Generated by Django 4.1.3 on 2023-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_create_nuevo_curso_form_carga_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_card',
            name='img_card',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='create_nuevo_publicacion',
            name='img_pub',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
