# Generated by Django 4.1.3 on 2023-04-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_create_nuevo_card_img_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='descrip_corta_curso',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='descrip_larga_curso',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='create_nuevo_publicacion',
            name='descrip_pub',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
