# Generated by Django 4.1.3 on 2023-04-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_create_nuevo_curso_descrip_corta_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_curso',
            name='descrip_larga_curso',
            field=models.CharField(max_length=600),
        ),
    ]
