# Generated by Django 4.1.3 on 2023-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_create_nuevo_curso_descrip_larga_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_class_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hospital', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='new_class_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sev', models.CharField(max_length=250)),
            ],
        ),
    ]
