# Generated by Django 4.1.3 on 2023-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_new_class_hospital_new_class_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_new_consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('credencial', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
    ]
