# Generated by Django 4.1.3 on 2023-05-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_create_nuevo_card_img_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_new_consultas',
            old_name='credencial',
            new_name='rut',
        ),
    ]
