# Generated by Django 4.1.3 on 2023-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_credencial_create_new_consultas_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_new_consultas_respondidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('fecha_respuesta', models.DateField()),
            ],
        ),
    ]
