# Generated by Django 4.1.3 on 2023-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_create_new_consultas_respondidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_new_consultas_respondidas',
            name='fecha_respuesta',
            field=models.DateTimeField(),
        ),
    ]
